api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination:
            enabled: true
            items_per_page: 5
            maximum_items_per_page: 20
            client_enabled: true  # Permet au client de désactiver la pagination
            client_items_per_page: true  # Permet au client de choisir le nombre d'éléments
    
    # Configuration des ressources
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
